// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJrSEgTopAATO3PSKyGBAbqsePZLWD02E',
    appId: '1:1020100556038:web:2bd99cef9a6a0436a0da87',
    messagingSenderId: '1020100556038',
    projectId: 'iti-ecommerce-app-2026',
    authDomain: 'iti-ecommerce-app-2026.firebaseapp.com',
    storageBucket: 'iti-ecommerce-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3qcqS1AJMMTOEjTSV1W0B0BDBQekVsqs',
    appId: '1:1020100556038:android:19e3e90c9113f49da0da87',
    messagingSenderId: '1020100556038',
    projectId: 'iti-ecommerce-app-2026',
    storageBucket: 'iti-ecommerce-app-2026.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaHyZo6nuDYJoodbxmMar_qw0Q2tUgc6Y',
    appId: '1:1020100556038:ios:8cad010ef550f942a0da87',
    messagingSenderId: '1020100556038',
    projectId: 'iti-ecommerce-app-2026',
    storageBucket: 'iti-ecommerce-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.itiEcommerceApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaHyZo6nuDYJoodbxmMar_qw0Q2tUgc6Y',
    appId: '1:1020100556038:ios:8cad010ef550f942a0da87',
    messagingSenderId: '1020100556038',
    projectId: 'iti-ecommerce-app-2026',
    storageBucket: 'iti-ecommerce-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.itiEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJrSEgTopAATO3PSKyGBAbqsePZLWD02E',
    appId: '1:1020100556038:web:a066ea94f80654e8a0da87',
    messagingSenderId: '1020100556038',
    projectId: 'iti-ecommerce-app-2026',
    authDomain: 'iti-ecommerce-app-2026.firebaseapp.com',
    storageBucket: 'iti-ecommerce-app-2026.firebasestorage.app',
  );
}
